<<<<<<< HEAD
spring.application.name=Project

server.port=8015
spring.datasource.url=jdbc:mysql://localhost:3306/learning
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


springdoc.swagger-ui.path=/swagger-ui.html
=======
spring.application.name=Ecom1
>>>>>>> c58055ec7fce2139764386f834d07fda803a5e57
